spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/data01?useUnicode=true&characterEncoding=utf-8
    username: root
    password: admin

logging:
  level:
    com:
      peko:
        mbp:
          dao: debug

#mybatis plus 设置
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml